// Code generated by swaggo/swag. DO NOT EDIT.
// 此文件为自动生成的 swagger 文档存根。
// 请在项目根目录执行以下命令重新生成完整文档：
//
//	go install github.com/swaggo/swag/cmd/swag@v1.8.12
//	swag init -g cmd/server/main.go --output docs --parseDependency --parseInternal
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "基于 Gin + GORM + Redis 的 Golang RESTful API 启动套件，内置微信小程序开发支持。",
        "title": "Go API Starter",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/example/go-api-starter"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "summary": "健康检查",
                "tags": ["系统"],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/auth/wechat-login": {
            "post": {
                "summary": "微信小程序登录",
                "description": "通过微信code换取用户JWT token",
                "tags": ["认证"],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["code"],
                        "properties": {
                            "code": {"type": "string", "description": "微信wx.login()返回的code"},
                            "nickname": {"type": "string"},
                            "avatar_url": {"type": "string"}
                        }
                    }
                }],
                "responses": {
                    "200": {"description": "登录成功，返回用户信息和token"}
                }
            }
        },
        "/api/v1/auth/refresh": {
            "post": {
                "summary": "刷新访问令牌",
                "tags": ["认证"],
                "consumes": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["refresh_token"],
                        "properties": {
                            "refresh_token": {"type": "string"}
                        }
                    }
                }],
                "responses": {"200": {"description": "新的token对"}}
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "summary": "获取当前用户信息",
                "tags": ["用户"],
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "用户信息"}}
            },
            "put": {
                "summary": "更新用户资料",
                "tags": ["用户"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "nickname": {"type": "string", "maxLength": 32},
                            "avatar_url": {"type": "string", "maxLength": 512},
                            "gender": {"type": "integer", "enum": [0, 1, 2], "description": "0未知 1男 2女"}
                        }
                    }
                }],
                "responses": {"200": {"description": "更新后的用户信息"}}
            }
        },
        "/api/v1/user/bind-phone": {
            "post": {
                "summary": "绑定手机号",
                "tags": ["用户"],
                "security": [{"BearerAuth": []}],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["phone"],
                        "properties": {
                            "phone": {"type": "string", "minLength": 11, "maxLength": 11}
                        }
                    }
                }],
                "responses": {"200": {"description": "绑定成功"}}
            }
        },
        "/api/v1/articles": {
            "get": {
                "summary": "获取文章列表",
                "tags": ["文章"],
                "parameters": [
                    {"in": "query", "name": "page", "type": "integer", "default": 1},
                    {"in": "query", "name": "page_size", "type": "integer", "default": 10}
                ],
                "responses": {"200": {"description": "分页文章列表"}}
            },
            "post": {
                "summary": "创建文章",
                "tags": ["文章"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["title", "content"],
                        "properties": {
                            "title": {"type": "string", "maxLength": 256},
                            "content": {"type": "string"},
                            "status": {"type": "integer", "enum": [0, 1], "description": "0草稿 1发布"}
                        }
                    }
                }],
                "responses": {"200": {"description": "创建成功"}}
            }
        },
        "/api/v1/articles/{id}": {
            "get": {
                "summary": "获取文章详情",
                "tags": ["文章"],
                "parameters": [{"in": "path", "name": "id", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "文章详情"}}
            },
            "put": {
                "summary": "更新文章",
                "tags": ["文章"],
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"in": "path", "name": "id", "required": true, "type": "integer"},
                    {"in": "body", "name": "body", "schema": {"type": "object"}}
                ],
                "responses": {"200": {"description": "更新成功"}}
            },
            "delete": {
                "summary": "删除文章",
                "tags": ["文章"],
                "security": [{"BearerAuth": []}],
                "parameters": [{"in": "path", "name": "id", "required": true, "type": "integer"}],
                "responses": {"200": {"description": "删除成功"}}
            }
        },
        "/api/v1/wechat/phone": {
            "post": {
                "summary": "获取微信手机号",
                "description": "小程序端调用 wx.getPhoneNumber() 获取 phoneCode，通过此接口换取真实手机号",
                "tags": ["微信"],
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "parameters": [{
                    "in": "body",
                    "name": "body",
                    "required": true,
                    "schema": {
                        "type": "object",
                        "required": ["code"],
                        "properties": {
                            "code": {"type": "string", "description": "wx.getPhoneNumber()返回的phoneCode"}
                        }
                    }
                }],
                "responses": {"200": {"description": "手机号信息"}}
            }
        },
        "/api/v1/wechat/message/subscribe": {
            "post": {
                "summary": "发送微信订阅消息",
                "tags": ["微信"],
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "发送成功"}}
            }
        },
        "/api/v1/wechat/message/customer": {
            "post": {
                "summary": "发送客服消息",
                "tags": ["微信"],
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "发送成功"}}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "格式：Bearer {token}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go API Starter",
	Description:      "基于 Gin + GORM + Redis 的 Golang RESTful API 启动套件，内置微信小程序开发支持。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
